# Generated by Django 3.0.3 on 2020-02-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64, verbose_name='아이디')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('서울특별시교육청', '서울'), ('부산광역시교육청', '부산'), ('대구광역시교육청', '대구'), ('인천광역시교육청', '인천'), ('광주광역시교육청', '광주'), ('대전광역시교육청', '대전'), ('울산광역시교육청', '울산'), ('세종특별자치시교육청', '세종'), ('경기도교육청', '경기'), ('강원도교육청', '강원'), ('충청북도교육청', '충북'), ('충청남도교육청', '충남'), ('전라북도교육청', '전북'), ('전라남도교육청', '전남'), ('경상북도교육청', '경북'), ('경상남도교육청', '경남'), ('제주특별자치도교육청', '제주')], max_length=32, verbose_name='교육청')),
                ('name', models.CharField(max_length=64, verbose_name='학교명')),
                ('s_code', models.IntegerField(verbose_name='학교코드')),
                ('ea', models.IntegerField(verbose_name='컴퓨터실 수')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
            ],
        ),
    ]
