# Generated by Django 3.2.4 on 2021-08-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('context', models.TextField(verbose_name='내용')),
                ('isshow', models.BooleanField(default=True, verbose_name='게시여부')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='수정날짜')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('서울특별시교육청', '서울'), ('부산광역시교육청', '부산'), ('대구광역시교육청', '대구'), ('인천광역시교육청', '인천'), ('광주광역시교육청', '광주'), ('대전광역시교육청', '대전'), ('울산광역시교육청', '울산'), ('세종특별자치시교육청', '세종'), ('경기도교육청', '경기'), ('강원도교육청', '강원'), ('충청북도교육청', '충북'), ('충청남도교육청', '충남'), ('전라북도교육청', '전북'), ('전라남도교육청', '전남'), ('경상북도교육청', '경북'), ('경상남도교육청', '경남'), ('제주특별자치도교육청', '제주')], max_length=32, verbose_name='교육청')),
                ('name', models.CharField(max_length=32, verbose_name='학교명')),
                ('s_code', models.IntegerField(verbose_name='학교코드')),
                ('ea', models.IntegerField(verbose_name='컴퓨터실 수')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
            ],
            options={
                'verbose_name': '학교',
                'verbose_name_plural': '학교',
            },
        ),
        migrations.CreateModel(
            name='IPs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16, unique=True, verbose_name='IP')),
                ('ip_first_date', models.DateTimeField(auto_now_add=True, verbose_name='첫 접속')),
                ('ip_recent_date', models.DateTimeField(auto_now=True, verbose_name='최근 접속')),
                ('ip_count', models.IntegerField(default=1, verbose_name='페이지 뷰')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': 'IPs',
                'verbose_name_plural': 'IP',
            },
        ),
        migrations.CreateModel(
            name='Comroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='컴퓨터', max_length=64, verbose_name='교실명')),
                ('caption', models.TextField(null=True, verbose_name='교실설명')),
                ('roomNo', models.IntegerField(verbose_name='교실번호')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='학교')),
            ],
            options={
                'verbose_name_plural': '컴퓨터실 정보',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64, verbose_name='아이디')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('realname', models.CharField(max_length=64, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('is_active', models.BooleanField(default=True, verbose_name='인증여부')),
                ('auth_key', models.CharField(blank=True, max_length=64, null=True, verbose_name='인증키')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': '학교관리자',
                'verbose_name_plural': '학교관리자',
            },
        ),
    ]
