# Generated by Django 3.0.3 on 2020-02-28 01:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '학교', 'verbose_name_plural': '학교'},
        ),
        migrations.AddField(
            model_name='adminuser',
            name='school',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='학교'),
            preserve_default=False,
        ),
    ]
