# Generated by Django 3.0.3 on 2020-03-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200311_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=32, verbose_name='학교명'),
        ),
    ]
