# Generated by Django 3.0.3 on 2020-03-18 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20200317_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16, unique=True, verbose_name='IP')),
                ('ip_first_date', models.DateTimeField(auto_now_add=True, verbose_name='첫 접속')),
                ('ip_recent_date', models.DateTimeField(auto_now=True, verbose_name='최근 접속')),
                ('ip_count', models.IntegerField(default=0, verbose_name='접속 횟수')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='학교')),
            ],
        ),
    ]
