# Generated by Django 3.0.3 on 2020-03-19 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_ips'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ips',
            options={'verbose_name': 'IPs', 'verbose_name_plural': 'IP'},
        ),
        migrations.AddField(
            model_name='notice',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정날짜'),
        ),
        migrations.AlterField(
            model_name='ips',
            name='ip_count',
            field=models.IntegerField(default=1, verbose_name='페이지 뷰'),
        ),
        migrations.AlterField(
            model_name='ips',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='학교'),
        ),
    ]
