# Generated by Django 3.0.3 on 2020-03-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_adminuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='auth_key',
            field=models.CharField(default='example', max_length=64, verbose_name='인증키'),
            preserve_default=False,
        ),
    ]
