# Generated by Django 3.2.4 on 2021-08-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=16, verbose_name='방')),
                ('is_available', models.BooleanField(default=True, verbose_name='사용가능여부')),
            ],
            options={
                'verbose_name': '방',
                'verbose_name_plural': '방',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=16, null=True, verbose_name='글쓴이')),
                ('visitor_image', models.ImageField(blank=True, null=True, upload_to='namu/%Y/%m/%d', verbose_name='사진')),
                ('visitor_text', models.TextField(verbose_name='내용')),
                ('visitor_pw', models.CharField(max_length=8, verbose_name='비밀번호')),
                ('is_show', models.BooleanField(default=True, verbose_name='게시')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='게시일')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namu.room', verbose_name='방')),
            ],
            options={
                'verbose_name': '방명록',
                'verbose_name_plural': '방명록',
            },
        ),
    ]
