# Generated by Django 3.0.3 on 2020-05-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': '방', 'verbose_name_plural': '방'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': '방명록', 'verbose_name_plural': '방명록'},
        ),
        migrations.AddField(
            model_name='visitor',
            name='writer',
            field=models.CharField(max_length=16, null=True, verbose_name='글쓴이'),
        ),
    ]
