# Generated by Django 3.2.4 on 2021-08-08 19:17

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1, verbose_name='학년')),
                ('classNo', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20)], verbose_name='반')),
                ('date', models.DateField(verbose_name='신청일')),
                ('time', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], verbose_name='예약시간')),
                ('teacher', models.CharField(max_length=16, verbose_name='선생님')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='예약등록시간')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.comroom', verbose_name='교실')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': '이용시간표',
                'verbose_name_plural': '이용시간표',
            },
        ),
        migrations.CreateModel(
            name='FixedTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_day', models.IntegerField(choices=[(0, '월'), (1, '화'), (2, '수'), (3, '목'), (4, '금')], default=0, verbose_name='요일')),
                ('fixed_time', models.IntegerField(choices=[(1, '1교시'), (2, '2교시'), (3, '3교시'), (4, '4교시'), (5, '5교시'), (6, '6교시')], default=1, verbose_name='시간')),
                ('fixed_name', models.CharField(max_length=32, verbose_name='내용')),
                ('fixed_from', models.DateField(default=django.utils.timezone.now, verbose_name='시작일')),
                ('fixed_until', models.DateField(default=datetime.datetime(2022, 2, 28, 0, 0), verbose_name='종료일')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('comroom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.comroom', verbose_name='교실')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': '고정시간',
                'verbose_name_plural': '고정시간',
            },
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['school', 'room'], name='timetable_t_school__e63b24_idx'),
        ),
    ]
