# Generated by Django 3.0.3 on 2020-02-28 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], verbose_name='학년')),
                ('classNo', models.IntegerField(verbose_name='반')),
                ('date', models.DateField(verbose_name='신청일')),
                ('time', models.IntegerField(verbose_name='예약시간')),
                ('roomNo', models.IntegerField(verbose_name='컴퓨터실번호')),
                ('teacher', models.CharField(max_length=16, verbose_name='선생님')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='예약등록시간')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='학교')),
            ],
        ),
    ]
