# Generated by Django 3.0.3 on 2020-03-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': '이용시간표', 'verbose_name_plural': '이용시간표'},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], verbose_name='예약시간'),
        ),
    ]
