# Generated by Django 3.2.4 on 2021-12-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timemap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timemap',
            options={'verbose_name': '일과시작시간', 'verbose_name_plural': '일과시작시간'},
        ),
        migrations.AddField(
            model_name='timetable',
            name='password',
            field=models.CharField(default='1111', max_length=16, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='fixedtimetable',
            name='fixed_time',
            field=models.IntegerField(choices=[(1, '1교시'), (2, '2교시'), (3, '3교시'), (4, '4교시'), (5, '5교시'), (6, '6교시'), (7, '7교시')], default=1, verbose_name='시간'),
        ),
        migrations.AlterField(
            model_name='timemap',
            name='first_start',
            field=models.CharField(choices=[('08:40', '08:40'), ('08:50', '08:50'), ('09:00', '09:00'), ('09:10', '09:10')], default='09:00', max_length=10, verbose_name='1교시 시작시간'),
        ),
    ]
