# Generated by Django 3.0.3 on 2020-03-13 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200311_1401'),
        ('timetable', '0005_auto_20200313_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Comroom', verbose_name='교실'),
        ),
    ]
