# Generated by Django 3.0.3 on 2020-03-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20200313_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='room',
        ),
    ]
