# Generated by Django 3.0.3 on 2020-03-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_timetable_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='roomNo',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='grade',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1, verbose_name='학년'),
        ),
    ]
