# Generated by Django 3.0.3 on 2020-03-17 03:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20200317_0308'),
        ('timetable', '0010_auto_20200316_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_day', models.IntegerField(choices=[(0, '월'), (1, '화'), (2, '수'), (3, '목'), (4, '금')], default=0, verbose_name='요일')),
                ('fixed_time', models.IntegerField(choices=[(1, '1교시'), (2, '2교시'), (3, '3교시'), (4, '4교시'), (5, '5교시'), (6, '6교시')], default=1, verbose_name='시간')),
                ('fixed_name', models.CharField(max_length=32, verbose_name='내용')),
                ('fixed_from', models.DateField(default=django.utils.timezone.now, verbose_name='시작일')),
                ('fixed_until', models.DateField(default=datetime.datetime(2021, 2, 28, 0, 0), verbose_name='종료일')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('comroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Comroom', verbose_name='교실')),
            ],
            options={
                'verbose_name': '고정시간',
                'verbose_name_plural': '고정시간',
            },
        ),
    ]
