# Generated by Django 3.0.3 on 2020-03-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_auto_20200318_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedtimetable',
            name='school',
        ),
    ]
