# Generated by Django 3.0.3 on 2020-03-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20200317_0308'),
        ('timetable', '0014_remove_fixedtimetable_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedtimetable',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='학교'),
        ),
    ]
