# Generated by Django 3.2.4 on 2021-06-07 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_fixedtimetable_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedtimetable',
            name='fixed_until',
            field=models.DateField(default=datetime.datetime(2022, 2, 28, 0, 0), verbose_name='종료일'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['school', 'room'], name='timetable_t_school__e63b24_idx'),
        ),
    ]
