# Generated by Django 3.2.4 on 2021-08-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disabled_ch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_name', models.CharField(max_length=64, verbose_name='채널명')),
                ('is_noticed', models.BooleanField(default=False, verbose_name='게시여부')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('noticed_date', models.DateTimeField(auto_now=True, verbose_name='게시날짜')),
            ],
            options={
                'verbose_name': '불가 채널',
                'verbose_name_plural': '불가 채널',
            },
        ),
        migrations.CreateModel(
            name='HTMLpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='페이지 이름')),
                ('page', models.TextField(verbose_name='페이지 내용')),
            ],
            options={
                'verbose_name': 'HTML Page',
                'verbose_name_plural': 'HTML Pages',
            },
        ),
        migrations.CreateModel(
            name='Notice_nocookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.TextField(verbose_name='공지')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='수정날짜')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
            },
        ),
        migrations.CreateModel(
            name='RollFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='학교', verbose_name='파일명')),
                ('roll_file', models.FileField(upload_to='rolls/%Y/')),
            ],
            options={
                'verbose_name': '명렬표 파일',
                'verbose_name_plural': '명렬표 파일',
            },
        ),
    ]
