# Generated by Django 3.0.3 on 2020-04-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disabled_ch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_name', models.CharField(max_length=64, verbose_name='채널명')),
                ('is_noticed', models.BooleanField(default=False, verbose_name='게시여부')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('noticed_date', models.DateTimeField(auto_now=True, verbose_name='게시날짜')),
            ],
            options={
                'verbose_name': 'Disabled_ch',
                'verbose_name_plural': 'Disabled_chs',
            },
        ),
    ]
