# Generated by Django 3.0.3 on 2020-04-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0002_auto_20200428_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_nocookie',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='수정날짜'),
        ),
    ]
