# Generated by Django 3.0.3 on 2020-04-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0003_auto_20200428_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='학교', verbose_name='파일명')),
                ('roll_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': '명렬표 파일',
                'verbose_name_plural': '명렬표 파일',
            },
        ),
    ]
