# Generated by Django 3.0.3 on 2020-05-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0006_auto_20200429_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='페이지 이름')),
                ('page', models.TextField(verbose_name='페이지 내용')),
            ],
        ),
    ]
