# Generated by Django 3.0.3 on 2020-05-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0007_htmlpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='htmlpage',
            options={'verbose_name': 'HTML Page', 'verbose_name_plural': 'HTML Pages'},
        ),
    ]
